version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000" # Map external port 80 to container port 3000
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      QUICKBOOKS_CLIENT_ID: ${QUICKBOOKS_CLIENT_ID}
      QUICKBOOKS_CLIENT_SECRET: ${QUICKBOOKS_CLIENT_SECRET}
      QUICKBOOKS_REDIRECT_URI: ${QUICKBOOKS_REDIRECT_URI}
      QUICKBOOKS_ENV: ${QUICKBOOKS_ENV}
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MYSQL_DATABASE: your_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"  # Expose Nginx to the host on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config
    depends_on:
      - app  # Ensure Nginx starts after the app

volumes:
  db_data:
