version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:3000" # Map external port 80 to container port 3000
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: YOUR_PASSWORD
      DB_DATABASE: your_database
      QUICKBOOKS_CLIENT_ID: YOUR_CLIENT_ID
      QUICKBOOKS_CLIENT_SECRET: YOUR_CLIENT_SECRET
      QUICKBOOKS_REDIRECT_URI: http://localhost:3000/callback
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
      MYSQL_DATABASE: your_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
